# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

#default: &default
#  adapter: sqlite3
#  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#  timeout: 5000

development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: poke_us3_manager_dev_db
  pool: 5
  username: root
  password: helmut407
  host: localhost

#test:
#  adapter: mysql2
#  encoding: utf8
#  reconnect: false
#  database: poke_us3_manager_test_db
#  pool: 5
#  username: sample
#  password: secret
#  host: localhost
#
#production:
#  adapter: mysql2
#  encoding: utf8
#  reconnect: false
#  database: poke_us3_manager_pro_db
#  pool: 5
#  username: sample
#  password: secret
#  host: localhost